#Server:
#  port: 6010
#spring:
#  cloud:
#    nacos:
#      discovery:
#        ##服务的注册
#        server-addr: 127.0.0.1:8848
#        ###  nacos 配置中心
#      config:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: api-wechat
#  profiles:
#    active: dev
#swagger:
#  enabled: