server:
  port: 80
spring:
  application:
    name: achen-springcloud-geteway
  cloud:
    gateway:
      discovery:
        locator:
          ####开启以服务id去注册中心上获取转发地址
          enabled: true
      routes:
        #全局唯一id  建议使用简单的 对应服务名
        - id: wechat
          #lb 查找注册中心的服务
#          uri: lb://api-wechat
          uri: lb://api-wechat
          filters:
           - StripPrefix=1
          predicates:
           - Path=/wechat/**

        - id: baidu
          #### 如果想要转发到外网 直接写地址
          uri: https://www.baidu.com
          filters:
            - StripPrefix=1
          ###匹配规则
          predicates:
            - Path=/baidu/**

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848